baseurl = "./"
languageCode = "es-ES"
title = "MAKINEA"
canonifyurls = true
paginate = 3

theme = "hugo-theme-lean-launch-page"

googleAnalytics = "UA-110194713-1"

[params]
tagline = "Plataforma digital de economía colaborativa en la que propietarios y usuarios de maquinaria agrícola realizan sus transacciones de alquiler de equipos rompiendo las barreras geográficas y resolviendo con un clic todos los aspectos administrativos: seguros, transporte, revisión de equipos, cobros, pagos y valoración de usuarios."
mailchimpURL = "//makinea.us17.list-manage.com/subscribe/post?u=e28258a76832fbe8708de5c9e&amp;id=1b9602c214"

twitter = "https://twitter.com/makineacom"
facebook = "https://facebook.com/makinea.makinea.3"
instagram = "https://instragram.com/makinea4102"
googleplus = "https://plus.google.com/113909664279245334016"
